# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: cdbfd9c
_src_path: gh:scipp/copier_template
description: Data reduction for NMX at the European Spallation Source.
max_python: '3.13'
min_python: '3.10'
namespace_package: ess
nightly_deps: scipp,sciline,scippnexus,plopp
orgname: scipp
prettyname: ESSnmx
projectname: essnmx
related_projects: Scipp,Sciline,Plopp,ScippNexus
year: 2025
