package:
  name: essnmx

  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..


{% set pyproject = load_file_data('pyproject.toml') %}
{% set dependencies = pyproject.get('project', {}).get('dependencies', {}) %}
{% set test_dependencies = pyproject.get('project', {}).get('optional-dependencies', {}).get('test', {}) %}


requirements:
  build:
    - setuptools
    - setuptools_scm
  run:
    - dask
    - python-graphviz
    - plopp
    - sciline>=23.9.1
    - scipp>=23.8.0
    - scippnexus>=23.9.0
    - pooch
    - defusedxml
    - python>=3.10
    - gemmi
    - pandas

  {# Conda does not allow spaces between package name and version, so remove them #}
  {% for package in dependencies %}
    - {% if package == "graphviz" %}python-graphviz{% else %}{{ package|replace(" ", "") }}{% endif %}
  {% endfor %}


test:
  imports:
    - ess.nmx
  requires:

  {# Conda does not allow spaces between package name and version, so remove them #}
  {% for package in test_dependencies %}
    - {% if package == "graphviz" %}python-graphviz{% else %}{{ package|replace(" ", "") }}{% endif %}
  {% endfor %}


  source_files:
    - pyproject.toml
    - tests/
  commands:
    # We ignore warnings during release package builds
    - python -m pytest -Wignore tests

build:
  noarch: python
  script:
    - python -m pip install .

about:
  home: https://github.com/scipp/essnmx
  license: BSD-3-Clause
  summary: Data reduction for NMX at the European Spallation Source.
  description: Data reduction for NMX at the European Spallation Source.
  dev_url: https://github.com/scipp/essnmx
  doc_url: https://scipp.github.io/essnmx
